// <auto-generated />
namespace Projet_Gestion_Ecole.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Moussa : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Moussa));
        
        string IMigrationMetadata.Id
        {
            get { return "202503210439102_Moussa"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
